apiVersion: mloc/v1
kind: SFTTask
metadata:
  name: llama32-3b-sft-full
  owner: demo
  annotations:
    description: "Full-parameter SFT on GSM8K (100 samples)"

spec:
  taskType: "sft"

  resources:
    replicas: 1
    hardware:
      cpu: "16"
      memory: "64Gi"
      gpu:
        type: "any"
        count: 2

  model:
    source:
      type: "huggingface"
      identifier: "meta-llama/Llama-3.2-3B-Instruct"
      revision: "main"

  data:
    dataset_name: "openai/gsm8k"
    config_name: "main"
    split: "train[:100]"
    prompt_column: "question"
    response_column: "answer"
    separator: "\n\nAnswer: "

  training:
    allow_multi_gpu: true
    visible_devices: "0,1"
    num_train_epochs: 2
    batch_size: 2
    gradient_accumulation_steps: 4
    learning_rate: 5.0e-5
    max_seq_length: 512
    logging_steps: 5
    save_steps: 50
    save_strategy: "steps"
    save_model: false
    gradient_checkpointing: true
    packing: false
    bf16: true

  output:
    destination:
      type: "local"
      path: "./runs/06_sft_full_single"
    artifacts:
      - "responses.json"
      - "logs"
      - "checkpoints"
