apiVersion: mloc/v1
kind: AgentTask
metadata:
  name: gsm8k-agent-search
  owner: demo
  annotations:
    description: "Retrieve web evidence to answer GSM8K-style math questions"

spec:
  taskType: "agent"

  resources:
    replicas: 1
    hardware:
      cpu: "2"
      memory: "4Gi"
      gpu:
        type: "any"
        count: 0

  configName: "simple_search"
  task: "Research techniques relevant to solving GSM8K math word problems and summarize 3 actionable tips."

  agent:
    timeout: 180

  output:
    destination:
      type: "local"
      path: "./runs/09_agent_query_search"
    artifacts:
      - "responses.json"
      - "agent_output.txt"
