apiVersion: mloc/v1
kind: LoRASFTTask
metadata:
  name: llama32-3b-lora-and-infer
  owner: demo
  annotations:
    description: "Train a LoRA adapter on GSM8K, then immediately run inference with the merged weights"

spec:
  taskType: "lora_sft"

  resources:
    replicas: 1
    hardware:
      cpu: "16"
      memory: "64Gi"
      gpu:
        type: "any"
        count: 2

  model:
    source:
      type: "huggingface"
      identifier: "meta-llama/Llama-3.2-3B-Instruct"
      revision: "main"

  stages:
    - name: lora-train
      spec:
        lora:
          r: 16
          alpha: 32
          dropout: 0.05
          bias: "none"
          target_modules:
            - "q_proj"
            - "k_proj"
            - "v_proj"
            - "o_proj"
          task_type: "CAUSAL_LM"
        data:
          dataset_name: "openai/gsm8k"
          config_name: "main"
          split: "train[:100]"
          prompt_column: "question"
          response_column: "answer"
          separator: "\n\nAnswer: "
        training:
          allow_multi_gpu: true
          visible_devices: "0,1"
          num_train_epochs: 1
          batch_size: 2
          gradient_accumulation_steps: 4
          learning_rate: 2.0e-4
          max_seq_length: 512
          logging_steps: 5
          save_steps: 40
          save_model: true
          gradient_checkpointing: true
          packing: false
          bf16: true
        output:
          destination:
            type: "http"
            url: "http://localhost:8000/api/v1/results"
          artifacts:
            - "responses.json"
            - "final_lora"
            - "logs"

    - name: lora-infer
      spec:
        taskType: "inference"
        parallel:
          enabled: true
          max_shards: 2
        model:
          adapters:
            - type: "lora"
              url: "${lora-train.result.final_lora_archive_url}"
              apply: "merge"
          vllm:
            tensor_parallel_size: 2
            gpu_memory_utilization: 0.6
            trust_remote_code: true
        data:
          type: "dataset"
          url: "openai/gsm8k"
          name: "main"
          split: "train[:200]"
          column: "question"
          shuffle: true
          seed: 99
        inference:
          system_prompt: |
            Use the adapter-trained reasoning style to solve the math word problem accurately.
          max_tokens: 256
          temperature: 0.2
          top_p: 0.9
        output:
          destination:
            type: "local"
            path: "./runs/11_lora_sft_plus_inference/inference"
          artifacts:
            - "responses.json"
            - "logs"
