# @package _global_
defaults:
  - /agents/examples/gaia@agent
  - _self_

exp_id: "gaia_test"

data:
  dataset: "GAIA_validation"
  # type: "single"
  # question_field: "question"
  # gt_field: "answer"

concurrency: 5

judge_model:
  model_provider:
    type: ${oc.env:JUDGE_LLM_TYPE}
    model: ${oc.env:JUDGE_LLM_MODEL}
    base_url: ${oc.env:JUDGE_LLM_BASE_URL}
    api_key: ${oc.env:JUDGE_LLM_API_KEY}
  model_params:
    temperature: 0.5
judge_concurrency: 64
