name: document
mode: builtin
activated_tools: null
config:
  parser: pymupdf  # pymupdf | chunkr
  # -- for chunkr
  # high_resolution: true
  # CHUNKR_API_KEY: ${oc.env:CHUNKR_API_KEY}
config_llm:
  model_provider:
    type: ${oc.env:UTU_LLM_TYPE}
    model: ${oc.env:UTU_LLM_MODEL}
    api_key: ${oc.env:UTU_LLM_API_KEY}
    base_url: ${oc.env:UTU_LLM_BASE_URL}
