# @package _global_
defaults:
  - /model/base@model
  - _self_

agent:
    name: mcp_sse_example
    instructions: "se the tools to answer the questions."

toolkits:
  example_sse_toolkit:
    name: example_sse_toolkit
    mode: mcp
    activated_tools: null
    mcp_transport: sse
    config:
      {"url": "http://localhost:8000/sse"}