# @package _global_
defaults:
  - /model/base@model
  - _self_

agent:
    name: mcp_streamablehttp_example
    instructions: "se the tools to answer the questions."

toolkits:
  example_streamablehttp_toolkit:
    name: example_streamablehttp_toolkit
    mode: mcp
    activated_tools: null
    mcp_transport: streamable_http
    config:
      {"url": "http://localhost:8000/mcp"}