# @package _global_
defaults:
  # - model: base
  - /model/base@planner_model
  - /model/base@reporter_model
  - /agents/simple_agents/search_agent@workers.SearchAgent
  - _self_


type: orchestra

# workers:
#   SearchAgent:
workers_info:
  - name: SearchAgent
    desc: information retrieval and data collection.
    strengths: Web search, information retrieval, research material collection, API data fetching
    weaknesses: No access to private databases, retrieval only (no content creation/modification)
  # - name: AnalysisAgent
  #   desc: analyze search results and extract insights
  #   strengths: Analyzing search results, extracting key information, summarizing findings, making connections between different pieces of information
  #   weaknesses: Can only analyze provided data, cannot perform new searches or create content
