# 在 GSM8K 上先生成草稿答案，再用自检提示复查并输出改写总结，演示 llama 1B 的线性推理组合。
apiVersion: mloc/v1
kind: InferenceTask
metadata:
  name: llama1b-gsm8k-self-check
  owner: demo
  annotations:
    description: "Three-stage reasoning chain with draft, critique, and final synthesis"

spec:
  taskType: "inference"

  resources:
    replicas: 1
    hardware:
      cpu: "12"
      memory: "48Gi"
      gpu:
        type: "any"
        count: 1
        memory: "24Gi"

  model:
    source:
      type: "huggingface"
      identifier: "meta-llama/Llama-3.2-1B-Instruct"
      revision: "main"
    vllm:
      gpu_memory_utilization: 0.85
      trust_remote_code: true

  stages:
    - name: draft-solver
      spec:
        taskType: "inference"
        data:
          type: "dataset"
          url: "openai/gsm8k"
          name: "main"
          split: "train[:64]"
          column: "question"
          shuffle: true
          seed: 2024
        inference:
          system_prompt: |
            Work step by step to solve the math problem. Label the reasoning clearly and end with "Draft answer: <value>".
          max_tokens: 256
          temperature: 0.25
          top_p: 0.9
        output:
          destination:
            type: "http"
            url: "http://localhost:8000/api/v1/results"
            timeoutSec: 30
          artifacts:
            - "responses.json"
            - "logs"

    - name: critique-reviewer
      spec:
        taskType: "inference"
        data:
          type: "graph_template"
          template:
            name: "two_column_briefing"
            columns:
              - label: "Example draft"
                expr: "draft-solver.result.items[0].output"
              - label: "Token usage"
                expr: "draft-solver.result.usage"
            options:
              intro:
                - "You are auditing reasoning quality for GSM8K math tutoring."
                - "Column A shows a representative draft solution."
                - "Column B lists usage metrics to keep responses concise."
              closing:
                - "Identify potential arithmetic or logical errors."
                - "Suggest a concise checklist for verifying future drafts."
        inference:
          system_prompt: |
            Review the draft solution. Flag issues, propose corrections, and produce an explicit verification checklist.
          max_tokens: 256
          temperature: 0.15
          top_p: 0.8
        output:
          destination:
            type: "http"
            url: "http://localhost:8000/api/v1/results"
            timeoutSec: 30
          artifacts:
            - "responses.json"
            - "logs"

    - name: final-rewrite
      spec:
        taskType: "inference"
        data:
          type: "graph_template"
          template:
            name: "two_column_briefing"
            columns:
              - label: "Draft pool"
                expr: "draft-solver.result.items"
              - label: "Review guidance"
                expr: "critique-reviewer.result.items[0].output"
            options:
              intro:
                - "You have draft answers and review guidance."
                - "Produce a polished solution style that incorporates the checklist."
              closing:
                - "Return a concise rubric plus an improved worked example."
        inference:
          system_prompt: |
            Merge the review feedback with the draft pool and output two parts: (1) a reusable rubric, (2) one improved example answer.
          max_tokens: 320
          temperature: 0.2
          top_p: 0.85
        output:
          destination:
            type: "http"
            url: "http://localhost:8000/api/v1/results"
            timeoutSec: 30
          artifacts:
            - "responses.json"
            - "logs"
