apiVersion: mloc/v1
kind: AgentTask
metadata:
  name: academic-paper-collector
  owner: researcher
  project: literature-review
  annotations:
    description: "Intelligent academic paper collection agent: automatically search and summarize papers in specific domains"

spec:
  taskType: "agent"

  configName: "examples/paper_collector"

  task: |
    Please search for 2 latest papers about reinforcement learning agents and provide summaries:
    - Search keywords: reinforcement learning agent
    - Provide paper titles, authors, and summaries

  resources:
    replicas: 1
    hardware:
      cpu: "4"
      memory: "8Gi"
      gpu:
        type: "any"
        count: 0

  agent:
    timeout: 300 # 5 minutes

  output:
    destination:
      type: "local"
      path: "paper_collector"  # Worker uses RESULTS_DIR
    artifacts:
      - "responses.json"           # MLOC standard output format
      - "agent_output.txt"         # Agent execution log
      - "paper_summary.md"         # Paper search results