apiVersion: mloc/v1
kind: AgentTask
metadata:
  name: agent-dataset-batch
  owner: researcher
  annotations:
    description: "Agent batch processing from HuggingFace dataset"

spec:
  taskType: "agent"

  configName: "examples/search_agent"

  data:
    type: "dataset"
    url: "hoanganhpham/qwen235_search_agent_sample"
    split: "train[:5]"
    column: "question"
    shuffle: true
    seed: 42

  resources:
    replicas: 1
    hardware:
      cpu: "4"
      memory: "8Gi"
      gpu:
        type: "any"
        count: 0

  agent:
    timeout: 300

  output:
    destination:
      type: "local"
      path: "agent_batch"
    artifacts:
      - "responses.json"
      - "batch_logs/"
      - "batch_summary.json"