# dag_inference_example.yaml
#
# Demonstrates a DAG where two parallel inference branches feed a final
# node that horizontally combines their outputs for a joint analysis.

apiVersion: mloc/v1
kind: InferenceTask
metadata:
  name: dag-two-branch-demo

spec:
  taskType: "inference"

  resources:
    replicas: 1
    hardware:
      cpu: "4"
      memory: "16GiB"

  model:
    source:
      type: "huggingface"
      identifier: "meta-llama/Llama-3.1-8B-Instruct"

  parallel:
    enabled: false

  graph:
    nodes:
      - name: branch-a
        spec:
          taskType: "inference"
          data:
            type: "list"
            items:
              - "List three long-term benefits of transitioning to renewable energy."
      - name: branch-b
        spec:
          taskType: "inference"
          data:
            type: "list"
            items:
              - "Identify two major challenges organizations face when adopting renewable energy."
      - name: synthesis
        dependsOn: ["branch-a", "branch-b"]
        spec:
          taskType: "inference"
          data:
            type: "graph_template"
            template:
              name: "two_column_briefing"
              columns:
                - label: "Benefits insight"
                  node: "branch-a"
                  path: "result.items[0].output"
                - label: "Challenges insight"
                  node: "branch-b"
                  path: "result.items[0].output"

  output:
    destination:
      type: "local"
      path: "./"
    artifacts:
      - "responses.json"
