apiVersion: mloc/v1
kind: InferenceTask
metadata:
  name: hf-tiny-demo
  owner: smoke-test
  annotations:
    description: "Run transformers text-generation using tiny GPT2"

spec:
  taskType: "inference"
  resources:
    replicas: 1
    hardware:
      cpu: "2"
      memory: "4Gi"
  model:
    source:
      type: "huggingface"
      identifier: "sshleifer/tiny-gpt2"
      revision: "main"
    transformers:
      device_map: "auto"
      trust_remote_code: false
  data:
    type: "list"
    items:
      - "MLOC orchestrator smoke test"
  inference:
    max_tokens: 16
    temperature: 0.1
    top_p: 0.95
  output:
    destination:
      type: "local"
      path: "./hf_tiny_demo"
    artifacts:
      - "responses.json"
      - "logs"
      - "artifacts"
