apiVersion: mloc/v1
kind: RetrievalTask
metadata:
  name: qdrant-rag-query
  owner: alice
  annotations:
    description: Query Qdrant with server-side embedding and return top passages
spec:
  taskType: rag
  resources:
    replicas: 1
    hardware:
      cpu: "2"
      memory: "2Gi"
  qdrant:
    url: "https://YOUR-CLUSTER-ID.us-east.aws.cloud.qdrant.io:6333"
    api_key: "${QDRANT_API_KEY}"
    collection: "demo_collection"
  embedding:
    model: "sentence-transformers/all-MiniLM-L6-v2"
  search:
    top_k: 5
  
  # Option A: Multiple fixed queries
  # data:
  #   type: list
  #   items:
  #     - "What is Qdrant?"
  #     - "How does server-side embedding work in Qdrant?"

  # Option B: Build queries from upstream results (enable spec.dependsOn)
  # data:
  #   type: graph_template
  #   template:
  #     name: two_column_briefing
  #     columns:
  #       - label: "q1"
  #         node: "<root>"
  #         path: "result.items[0].output"
  #       - label: "q2"
  #         expr: "<root>.result.items[1].output"

  # Option C: Hugging Face dataset (one query per row)
  data:
    type: list
    items:
      - "What is Qdrant?"
      - "How does server-side embedding work in Qdrant?"

  output:
    destination:
      type: "local"
      path: "./"
    artifacts:
      - "responses.json"

