apiVersion: mloc/v1
kind: RetrievalTask
metadata:
  name: qdrant-rag-query
  owner: alice
  annotations:
    description: Query Qdrant with server-side embedding and return top passages
spec:
  taskType: rag
  resources:
    replicas: 1
    hardware:
      cpu: "2"
      memory: "2Gi"
  qdrant:
    url: "https://YOUR-CLUSTER-ID.us-east.aws.cloud.qdrant.io:6333"
    api_key: "${QDRANT_API_KEY}"
    collection: "demo_collection"
  embedding:
    model: "sentence-transformers/all-MiniLM-L6-v2"
  search:
    top_k: 5
  query: "This is a query example"

