# sft_mistral_7b.yaml
#
# Example supervised fine-tuning task that uses the new TRL-based SFT executor.
# Update the model identifier and dataset configuration to match your workload.

apiVersion: mloc/v1
kind: SFTTask
metadata:
  name: gpt2-sft-demo

spec:
  taskType: "sft"

  resources:
    replicas: 1
    hardware:
      cpu: "8"
      memory: "32GiB"
      gpu:
        count: 1
        type: "any"

  model:
    source:
      type: "huggingface"
      identifier: "mistralai/Mistral-7B-Instruct-v0.3"

  data:
    dataset_name: "openai/gsm8k"
    config_name: "main"
    split: "train[:1%]"
    prompt_column: "question"
    response_column: "answer"
    separator: "\n\nAnswer: "
    max_samples: 200

  training:
    num_train_epochs: 1
    batch_size: 2
    gradient_accumulation_steps: 4
    learning_rate: 5.0e-5
    max_seq_length: 512
    logging_steps: 5
    save_steps: 50
    save_model: true

  output:
    destination:
      type: "local"
      path: "/mnt/mloc-results"
    artifacts:
      - "responses.json"
      - "final_model"
