# sft_llama_3b.yaml
apiVersion: mloc/v1
kind: SFTTask
metadata:
  name: llama-3b-sft-demo

spec:
  taskType: "sft"

  resources:
    replicas: 1
    hardware:
      cpu: "8"
      memory: "32GiB"
      gpu:
        count: 2
        type: "any"

  model:
    source:
      type: "huggingface"
      identifier: "meta-llama/Llama-3.2-3B-Instruct"

  data:
    dataset_name: "openai/gsm8k"
    config_name: "main"
    split: "train[:5%]"
    prompt_column: "question"
    response_column: "answer"
    separator: "\n\nAnswer: "
    max_samples: 200

  training:
    allow_multi_gpu: true
    visible_devices: "0,1"
    num_train_epochs: 2
    batch_size: 2                      # == DS.train_micro_batch_size_per_gpu
    gradient_accumulation_steps: 4     # == DS.gradient_accumulation_steps
    learning_rate: 5.0e-5
    max_seq_length: 512
    logging_steps: 5
    save_steps: 50
    save_model: true
    gradient_checkpointing: true
    packing: false
    fp16: false
    bf16: true
    deepspeed:
      zero_optimization:
        stage: 2
        offload_optimizer:
          device: cpu
          pin_memory: true
        allgather_partitions: true
        allgather_bucket_size: 200000000
        reduce_scatter: true
        reduce_bucket_size: 200000000
        overlap_comm: true
        contiguous_gradients: true
      bf16:
        enabled: true
      zero_allow_untested_optimizer: true
      train_micro_batch_size_per_gpu: 2
      gradient_accumulation_steps: 4

  output:
    destination:
      type: "local"
      path: "./sft_llama_3b"
    artifacts:
      - "responses.json"
      - "final_model"
