# sft_llama3b_fsdp.yaml
apiVersion: mloc/v1
kind: SFTTask
metadata:
  name: llama-3b-sft-fsdp

spec:
  taskType: "sft"

  resources:
    replicas: 1
    hardware:
      cpu: "8"
      memory: "32GiB"
      gpu:
        count: 2
        type: "any"

  model:
    source:
      type: "huggingface"
      identifier: "meta-llama/Llama-3.2-3B-Instruct"

  data:
    dataset_name: "openai/gsm8k"
    config_name: "main"
    split: "train[:5%]"
    prompt_column: "question"
    response_column: "answer"
    separator: "\n\nAnswer: "
    max_samples: 200

  training:
    # 多卡可见
    allow_multi_gpu: true
    visible_devices: "0,1"

    # 训练超参（唯一真源）
    num_train_epochs: 2
    batch_size: 2
    gradient_accumulation_steps: 4
    learning_rate: 5.0e-5
    max_seq_length: 512
    logging_steps: 5
    save_steps: 50
    save_strategy: "steps"
    save_model: true

    # 稳定性/显存
    gradient_checkpointing: true
    packing: false
    fp16: false
    bf16: true

    # === FSDP 开启 ===
    fsdp: "full_shard auto_wrap"
    fsdp_config:
      transformer_layer_cls_to_wrap: "LlamaDecoderLayer"
      min_num_params: 100000000         # 1e8；按需调小可包得更细
      sync_module_states: true
      forward_prefetch: true
      limit_all_gathers: true
      use_orig_params: true

  output:
    destination:
      type: "local"
      path: "./sft_llama_3b"
    artifacts:
      - "responses.json"
      - "final_model"
