# @package _global_
defaults:
  - /model/base@model
  # - /tools/search@toolkits.search
  - /tools/bash@toolkits.bash
  - _self_

agent:
    name: gui-agent-toolmaker
    instructions: "You are a helpful assistant."
