# @package _global_
defaults:
  - /model/base@planner_model
  - /model/base@reporter_model
  - /agents/simple_agents/search_agent@workers.SearchAgent
  - /agents/simple_agents/paper_summarize_agent@workers.PaperSummarizeAgent
  - _self_


type: orchestra

planner_config:
  examples_path: planner_examples_data.json

workers_info:
  - name: SearchAgent
    desc: information retrieval and data collection.
    strengths: Web search, information retrieval, research material collection, API data fetching
    weaknesses: No access to private databases, retrieval only (no content creation/modification)
  - name: PaperSummarizeAgent
    desc: explore and summarize the given paper, return the abstract, related papers, core methods and experiment conclusions.
    strengths: Analyzing scientific papers, extracting key information or related information, summarizing content.
    weaknesses: No access to the internet.