# @package _global_
defaults:
  - /model/base@planner_model
  - /model/base@reporter_model
  - /agents/simple_agents/search_agent@workers.SearchAgent
  - _self_


type: orchestra

planner_config:
  examples_path: planner_examples_data.json

workers_info:
  - name: SearchAgent
    desc: information retrieval and data collection.
    strengths: Web search, information retrieval, research material collection, API data fetching
    weaknesses: No access to private databases, retrieval only (no content creation/modification)